{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app-chart.fullname" . }}-secret
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
{{- end }}
